<?php

namespace Database\Seeders;

use App\Models\MotivoRechazo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MotivosRechazosSeeders extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        MotivoRechazo::insert([
            ['id'=>1,  'area' =>'CC',  'causa_rechazo' => 'Agallas Verdosas', 'codigo_seccion'=>4, 'vida_util' => 0],
            ['id'=>3,  'area' =>'CC',  'causa_rechazo' => 'Deshidratación', 'codigo_seccion'=>4, 'vida_util' => NULL],
            ['id'=>5,  'area' =>'CC',  'causa_rechazo' => 'Mal Eviscerado', 'codigo_seccion'=>4, 'vida_util' => NULL],
            ['id'=>6,  'area' =>'CC',  'causa_rechazo' => 'Mariscos Muertos', 'codigo_seccion'=>4, 'vida_util' => NULL],
            ['id'=>7,  'area' =>'CC',  'causa_rechazo' => 'Mariscos Quebrados ', 'codigo_seccion'=>4, 'vida_util' => NULL],
            ['id'=>8,  'area' =>'CC',  'causa_rechazo' => 'Presencia Excesiva de Parásitos', 'codigo_seccion'=>4, 'vida_util' => NULL],
            ['id'=>10, 'area' => 'CC', 'causa_rechazo'  => 'Sin Aletas', 'codigo_seccion'=>4, 'vida_util' => NULL],
            ['id'=>11, 'area' => 'CC', 'causa_rechazo'  => 'Sin Eviscerar', 'codigo_seccion'=>4, 'vida_util' => NULL],
            ['id'=>12, 'area' => 'CC', 'causa_rechazo'  => 'Sin Gel Pack o Hielo', 'codigo_seccion'=>4, 'vida_util' => NULL],
            ['id'=>13, 'area' => 'CC', 'causa_rechazo'  => 'Deformacion', 'codigo_seccion'=>5, 'vida_util' => 1],
            ['id'=>14, 'area' => 'CC', 'causa_rechazo'  => 'Desgrane de Producto', 'codigo_seccion'=>5, 'vida_util' => 1],
            ['id'=>15, 'area' => 'CC', 'causa_rechazo'  => 'Envases con Filtracion', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>16, 'area' => 'CC', 'causa_rechazo'  => 'Envases Hinchados', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>17, 'area' => 'CC', 'causa_rechazo'  => 'Exceso de Fluorescencia', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>18, 'area' => 'CC', 'causa_rechazo'  => 'Exceso de Vacuolas', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>19, 'area' => 'CC', 'causa_rechazo'  => 'Grietas', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>20, 'area' => 'CC', 'causa_rechazo'  => 'Mal Prensado', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>22, 'area' => 'CC', 'causa_rechazo'  => 'Presencia de Hongos', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>23, 'area' => 'CC', 'causa_rechazo'  => 'Textura Blanda', 'codigo_seccion'=>5, 'vida_util' => 1],
            ['id'=>26, 'area' => 'CC', 'causa_rechazo'  => 'Exceso de Burbujas', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>29, 'area' => 'CC', 'causa_rechazo'  => 'Perdida de Vacio', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>30, 'area' => 'CC', 'causa_rechazo'  => 'Presencia de pelo', 'codigo_seccion'=>5, 'vida_util' => NULL],
            ['id'=>31, 'area' => 'CC', 'causa_rechazo'  => 'Heridas', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>32, 'area' => 'CC', 'causa_rechazo'  => 'Presencia de insectos', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>33, 'area' => 'CC', 'causa_rechazo'  => 'Presencia de residuos químicos', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>34, 'area' => 'CC', 'causa_rechazo'  => 'Pudricion', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>35, 'area' => 'CC', 'causa_rechazo'  => 'Pelonas', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>36, 'area' => 'CC', 'causa_rechazo'  => 'Coloración', 'codigo_seccion'=>6, 'vida_util' => NULL],
            ['id'=>37, 'area' => 'CC', 'causa_rechazo'  => 'Daño por insecto', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>39, 'area' => 'CC', 'causa_rechazo'  => 'Sobrecalibre', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>41, 'area' => 'CC', 'causa_rechazo'  => 'Fumagina', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>42, 'area' => 'CC', 'causa_rechazo'  => 'Golpe de sol', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>43, 'area' => 'CC', 'causa_rechazo'  => 'Hojas quemadas/ Tip Burn', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>44, 'area' => 'CC', 'causa_rechazo'  => 'Machucones', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>45, 'area' => 'CC', 'causa_rechazo'  => 'Sobremadurez', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>46, 'area' => 'CC', 'causa_rechazo'  => 'Manchas', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>47, 'area' => 'CC', 'causa_rechazo'  => 'Corazon Pardo/ Acuoso', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>48, 'area' => 'CC', 'causa_rechazo'  => 'Pedunculo ', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>49, 'area' => 'CC', 'causa_rechazo'  => 'Exceso/ Falta de cera', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>50, 'area' => 'CC', 'causa_rechazo'  => 'Carozo Partido', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>51, 'area' => 'CC', 'causa_rechazo'  => 'Russet', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>52, 'area' => 'CC', 'causa_rechazo'  => 'Plateado', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>53, 'area' => 'CC', 'causa_rechazo'  => 'Reticulado', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>54, 'area' => 'CC', 'causa_rechazo'  => 'Brotación', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>55, 'area' => 'CC', 'causa_rechazo'  => 'Pitting', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>56, 'area' => 'CC', 'causa_rechazo'  => 'Cracking', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>57, 'area' => 'CC', 'causa_rechazo'  => 'Venturia ', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>58, 'area' => 'CC', 'causa_rechazo'  => 'Lenticelosis', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>60, 'area' => 'CC', 'causa_rechazo'  => 'Daño por frio', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>62, 'area' => 'CC', 'causa_rechazo'  => 'Creasing', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>64, 'area' => 'CC', 'causa_rechazo'  => 'Rugosidad', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>66, 'area' => 'CC', 'causa_rechazo'  => 'Casposa', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>67, 'area' => 'CC', 'causa_rechazo'  => 'Daño por tizón', 'codigo_seccion'=>6, 'vida_util' => NULL],
            ['id'=>68, 'area' => 'CC', 'causa_rechazo'  => 'Pardeamiento', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>69, 'area' => 'CC', 'causa_rechazo'  => 'Hojas amarillas', 'codigo_seccion'=>6, 'vida_util' => 1],
            ['id'=>70, 'area' => 'CC', 'causa_rechazo'  => 'Presencia de materia extraña', 'codigo_seccion'=>0, 'vida_util' => 1],
            ['id'=>71, 'area' => 'CC', 'causa_rechazo'  => 'Sin documentacion', 'codigo_seccion'=>0, 'vida_util' => NULL],
            ['id'=>72, 'area' => 'CC', 'causa_rechazo'  => 'Envases sucios (tierra, barro, suciedad)', 'codigo_seccion'=>0, 'vida_util' => 1],
            ['id'=>73, 'area' => 'CC', 'causa_rechazo'  => 'Cajas en mal estado (sucia, deteriorada, humedas, quebrada)', 'codigo_seccion'=>0, 'vida_util' => NULL],
            ['id'=>74, 'area' => 'CC', 'causa_rechazo'  => 'Mal Sellado / Sin Sello', 'codigo_seccion'=>0, 'vida_util' => NULL],
            ['id'=>75, 'area' => 'CC', 'causa_rechazo'  => 'Analisis de Control de Calidad', 'codigo_seccion'=>0, 'vida_util' => NULL],
            ['id'=>76, 'area' => 'CC', 'causa_rechazo'  => 'Bajo peso', 'codigo_seccion'=>0, 'vida_util' => NULL],
            ['id'=>77, 'area' => 'CC', 'causa_rechazo'  => 'Mal Olor', 'codigo_seccion'=>0, 'vida_util' => NULL],
            ['id'=>79, 'area' => 'CC', 'causa_rechazo'  => 'No cumple temperatura del producto ', 'codigo_seccion'=>0, 'vida_util' => NULL],
            ['id'=>80, 'area' => 'CC', 'causa_rechazo'  => 'Daño mecánico', 'codigo_seccion'=>0, 'vida_util' => NULL],
            ['id'=>81, 'area' => 'CC', 'causa_rechazo'  => 'Fecha ilegible', 'codigo_seccion'=>0, 'vida_util' => 1],
            ['id'=>83, 'area' => 'CC', 'causa_rechazo'  => 'Fuera de rango de vida util aceptable', 'codigo_seccion'=>0, 'vida_util' => 1],
            ['id'=>88, 'area' => 'OP', 'causa_rechazo'  => 'Producto no facturado', 'codigo_seccion'=>99, 'vida_util' => NULL],
            ['id'=>90, 'area' => 'OP', 'causa_rechazo'  => 'Pallet quebrados o mal estado', 'codigo_seccion'=>99, 'vida_util' => NULL],
            ['id'=>92, 'area' => 'OP', 'causa_rechazo'  => 'Mala Estiba', 'codigo_seccion'=>99, 'vida_util' => NULL],
            ['id'=>93, 'area' => NULL, 'causa_rechazo'  => 'Bajo Calibre', 'codigo_seccion'=>7, 'vida_util' => 1],
            ['id'=>94, 'area' => NULL, 'causa_rechazo'  => 'Caracteristicas organolepticas alteradas ', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>95, 'area' => NULL, 'causa_rechazo'  => 'Bajo porcentaje de jugo', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>96, 'area' => NULL, 'causa_rechazo'  => 'Bitter pit ', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>97, 'area' => NULL, 'causa_rechazo'  => 'Caida de pallet ', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>98, 'area' => NULL, 'causa_rechazo'  => 'Condensacion', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>99, 'area' => NULL, 'causa_rechazo'  => 'Envases abollados', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>100, 'area' => NULL, 'causa_rechazo'  =>  'Envases con oxido', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>101, 'area' => NULL , 'causa_rechazo' =>  'Envases rotos', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>102, 'area' => NULL , 'causa_rechazo' =>  'Fecha adulterada', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>103, 'area' => NULL , 'causa_rechazo' =>  'Fechas Mezcladas ', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>104, 'area' => NULL , 'causa_rechazo' =>  'Logo no corresponde', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>106, 'area' => NULL , 'causa_rechazo' =>  'Mal Etiquetado', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>107, 'area' => NULL , 'causa_rechazo' =>  'No cumple ley 20.606', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>108, 'area' => NULL , 'causa_rechazo' =>  'Producto en veda', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>109, 'area' => NULL , 'causa_rechazo' =>  'Resolución transporte vencida ', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>110, 'area' => NULL , 'causa_rechazo' =>  'Rotulacion incorrecta / incompleta', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>111, 'area' => NULL , 'causa_rechazo' =>  'Sin etiquetas ', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>112, 'area' => NULL , 'causa_rechazo' =>  'Sin Logo ', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>113, 'area' => NULL , 'causa_rechazo' =>  'Sin Resolucion Sanitaria', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>114, 'area' => NULL , 'causa_rechazo' =>  'Transporte no corresponde al tipo de producto ', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>115, 'area' => NULL , 'causa_rechazo' =>  'Uva proveniente de zona reglamentada ', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>116, 'area' => NULL , 'causa_rechazo' =>  'Variedad no correspondiente ', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>117, 'area' => NULL , 'causa_rechazo' =>  'Variedades mezcladas ', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>118, 'area' => NULL , 'causa_rechazo' =>  'Vencido', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>119, 'area' => NULL , 'causa_rechazo' =>  'Exceso de Exudación', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>120, 'area' => NULL , 'causa_rechazo' =>  'Mal Desposte', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>121, 'area' => NULL , 'causa_rechazo' =>  'Bolsa SAG', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>122, 'area' => NULL , 'causa_rechazo' =>  'Golpe de Frío', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>123, 'area' => NULL , 'causa_rechazo' =>  'Brix', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>124, 'area' => NULL , 'causa_rechazo' =>  'Bufado', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>125, 'area' => NULL , 'causa_rechazo' =>  'Daño por Helada', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>126, 'area' => NULL , 'causa_rechazo' =>  'Daño por Tizon', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>127, 'area' => NULL , 'causa_rechazo' =>  'Escaldado', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>128, 'area' => NULL , 'causa_rechazo' =>  'Peteca', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>129, 'area' => NULL , 'causa_rechazo' =>  'Capacidad', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>130, 'area' => NULL , 'causa_rechazo' =>  'No solicitado', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>131, 'area' => NULL , 'causa_rechazo' =>  'Pallet yugo', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>132, 'area' => NULL , 'causa_rechazo' =>  'Código SAP Incorrecto', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>133, 'area' => NULL , 'causa_rechazo' =>  'Orden de compra incorrecta', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>134, 'area' => NULL , 'causa_rechazo' =>  'Exceso de agua', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>135, 'area' => NULL , 'causa_rechazo' =>  'Oxidacion', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>136, 'area' => NULL , 'causa_rechazo' =>  'Oleocelosis', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>137, 'area' => NULL , 'causa_rechazo' =>  'Daño por Roedor', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>138, 'area' => NULL , 'causa_rechazo' =>  'Proveedor suspendido', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>139, 'area' => NULL , 'causa_rechazo' =>  'Inconsistencia vida útil', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>140, 'area' => NULL , 'causa_rechazo' =>  'Sin fecha de elaboración y/o Vencimiento', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>142, 'area' => NULL , 'causa_rechazo' =>  'Frutos inmaduros', 'codigo_seccion' => NULL, 'vida_util' => NULL],
            ['id'=>143, 'area' => NULL , 'causa_rechazo' =>  'Falta de madurez', 'codigo_seccion' => NULL, 'vida_util' => 1],
            ['id'=>144, 'area' => NULL , 'causa_rechazo' =>  'Exceso de tallo', 'codigo_seccion' => NULL, 'vida_util' => 0],
            ['id'=>145, 'area' => NULL , 'causa_rechazo' =>  'Sin lote', 'codigo_seccion' => NULL, 'vida_util' => 0]
        ]);
    }
}
