<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        Pais::insert([
            ['code'=> 4, 'nombre' => 'Afganistán' , 'codigo_interno' => NULL],
            ['code'=> 248, 'nombre' => 'Islas Gland' , 'codigo_interno' => NULL],
            ['code'=> 8, 'nombre' => 'Albania' , 'codigo_interno' => NULL],
            ['code'=> 276, 'nombre' => 'Alemania' , 'codigo_interno' => NULL],
            ['code'=> 20, 'nombre' => 'Andorra' , 'codigo_interno' => NULL],
            ['code'=> 24, 'nombre' => 'Angola' , 'codigo_interno' => NULL],
            ['code'=> 660, 'nombre' => 'Anguilla' , 'codigo_interno' => NULL],
            ['code'=> 10, 'nombre' => 'Antártida' , 'codigo_interno' => NULL],
            ['code'=> 28, 'nombre' => 'Antigua y Barbuda' , 'codigo_interno' => NULL],
            ['code'=> 530, 'nombre' => 'Antillas Holandesas' , 'codigo_interno' => NULL],
            ['code'=> 682, 'nombre' => 'Arabia Saudí' , 'codigo_interno' => NULL],
            ['code'=> 12, 'nombre' => 'Argelia' , 'codigo_interno' => NULL],
            ['code'=> 32, 'nombre' => 'Argentina' , 'codigo_interno' => NULL],
            ['code'=> 51, 'nombre' => 'Armenia' , 'codigo_interno' => NULL],
            ['code'=> 533, 'nombre' => 'Aruba' , 'codigo_interno' => NULL],
            ['code'=> 36, 'nombre' => 'Australia' , 'codigo_interno' => NULL],
            ['code'=> 40, 'nombre' => 'Austria' , 'codigo_interno' => NULL],
            ['code'=> 31, 'nombre' => 'Azerbaiyán' , 'codigo_interno' => NULL],
            ['code'=> 44, 'nombre' => 'Bahamas' , 'codigo_interno' => NULL],
            ['code'=> 48, 'nombre' => 'Bahréin' , 'codigo_interno' => NULL],
            ['code'=> 50, 'nombre' => 'Bangladesh' , 'codigo_interno' => NULL],
            ['code'=> 52, 'nombre' => 'Barbados' , 'codigo_interno' => NULL],
            ['code'=> 112, 'nombre' => 'Bielorrusia' , 'codigo_interno' => NULL],
            ['code'=> 56, 'nombre' => 'Bélgica' , 'codigo_interno' => NULL],
            ['code'=> 84, 'nombre' => 'Belice' , 'codigo_interno' => NULL],
            ['code'=> 204, 'nombre' => 'Benin' , 'codigo_interno' => NULL],
            ['code'=> 60, 'nombre' => 'Bermudas' , 'codigo_interno' => NULL],
            ['code'=> 64, 'nombre' => 'Bhután' , 'codigo_interno' => NULL],
            ['code'=> 68, 'nombre' => 'Bolivia' , 'codigo_interno' => NULL],
            ['code'=> 70, 'nombre' => 'Bosnia y Herzegovina' , 'codigo_interno' => NULL],
            ['code'=> 72, 'nombre' => 'Botsuana' , 'codigo_interno' => NULL],
            ['code'=> 74, 'nombre' => 'Isla Bouvet' , 'codigo_interno' => NULL],
            ['code'=> 76, 'nombre' => 'Brasil' , 'codigo_interno' => NULL],
            ['code'=> 96, 'nombre' => 'Brunéi' , 'codigo_interno' => NULL],
            ['code'=> 100, 'nombre' => 'Bulgaria' , 'codigo_interno' => NULL],
            ['code'=> 854, 'nombre' => 'Burkina Faso' , 'codigo_interno' => NULL],
            ['code'=> 108, 'nombre' => 'Burundi' , 'codigo_interno' => NULL],
            ['code'=> 132, 'nombre' => 'Cabo Verde' , 'codigo_interno' => NULL],
            ['code'=> 136, 'nombre' => 'Islas Caimán' , 'codigo_interno' => NULL],
            ['code'=> 116, 'nombre' => 'Camboya' , 'codigo_interno' => NULL],
            ['code'=> 120, 'nombre' => 'Camerún' , 'codigo_interno' => NULL],
            ['code'=> 124, 'nombre' => 'Canadá' , 'codigo_interno' => NULL],
            ['code'=> 140, 'nombre' => 'República Centroafricana' , 'codigo_interno' => NULL],
            ['code'=> 148, 'nombre' => 'Chad' , 'codigo_interno' => NULL],
            ['code'=> 203, 'nombre' => 'República Checa' , 'codigo_interno' => NULL],
            ['code'=> 152, 'nombre' => 'Chile' , 'codigo_interno' => NULL],
            ['code'=> 156, 'nombre' => 'China' , 'codigo_interno' => NULL],
            ['code'=> 196, 'nombre' => 'Chipre' , 'codigo_interno' => NULL],
            ['code'=> 162, 'nombre' => 'Isla de Navidad' , 'codigo_interno' => NULL],
            ['code'=> 336, 'nombre' => 'Ciudad del Vaticano' , 'codigo_interno' => NULL],
            ['code'=> 166, 'nombre' => 'Islas Cocos' , 'codigo_interno' => NULL],
            ['code'=> 170, 'nombre' => 'Colombia' , 'codigo_interno' => NULL],
            ['code'=> 174, 'nombre' => 'Comoras' , 'codigo_interno' => NULL],
            ['code'=> 180, 'nombre' => 'República Democrática del Congo' , 'codigo_interno' => NULL],
            ['code'=> 178, 'nombre' => 'Congo' , 'codigo_interno' => NULL],
            ['code'=> 184, 'nombre' => 'Islas Cook' , 'codigo_interno' => NULL],
            ['code'=> 408, 'nombre' => 'Corea del Norte' , 'codigo_interno' => NULL],
            ['code'=> 410, 'nombre' => 'Corea del Sur' , 'codigo_interno' => NULL],
            ['code'=> 384, 'nombre' => 'Costa de Marfil' , 'codigo_interno' => NULL],
            ['code'=> 188, 'nombre' => 'Costa Rica' , 'codigo_interno' => NULL],
            ['code'=> 191, 'nombre' => 'Croacia' , 'codigo_interno' => NULL],
            ['code'=> 192, 'nombre' => 'Cuba' , 'codigo_interno' => NULL],
            ['code'=> 208, 'nombre' => 'Dinamarca' , 'codigo_interno' => NULL],
            ['code'=> 212, 'nombre' => 'Dominica' , 'codigo_interno' => NULL],
            ['code'=> 214, 'nombre' => 'República Dominicana' , 'codigo_interno' => NULL],
            ['code'=> 218, 'nombre' => 'Ecuador' , 'codigo_interno' => NULL],
            ['code'=> 818, 'nombre' => 'Egipto' , 'codigo_interno' => NULL],
            ['code'=> 222, 'nombre' => 'El Salvador' , 'codigo_interno' => NULL],
            ['code'=> 784, 'nombre' => 'Emiratos Árabes Unidos' , 'codigo_interno' => NULL],
            ['code'=> 232, 'nombre' => 'Eritrea' , 'codigo_interno' => NULL],
            ['code'=> 703, 'nombre' => 'Eslovaquia' , 'codigo_interno' => NULL],
            ['code'=> 705, 'nombre' => 'Eslovenia' , 'codigo_interno' => NULL],
            ['code'=> 724, 'nombre' => 'España' , 'codigo_interno' => NULL],
            ['code'=> 581, 'nombre' => 'Islas ultramarinas de Estados Unidos' , 'codigo_interno' => NULL],
            ['code'=> 840, 'nombre' => 'Estados Unidos' , 'codigo_interno' => NULL],
            ['code'=> 233, 'nombre' => 'Estonia' , 'codigo_interno' => NULL],
            ['code'=> 231, 'nombre' => 'Etiopía' , 'codigo_interno' => NULL],
            ['code'=> 234, 'nombre' => 'Islas Feroe' , 'codigo_interno' => NULL],
            ['code'=> 608, 'nombre' => 'Filipinas' , 'codigo_interno' => NULL],
            ['code'=> 246, 'nombre' => 'Finlandia' , 'codigo_interno' => NULL],
            ['code'=> 242, 'nombre' => 'Fiyi' , 'codigo_interno' => NULL],
            ['code'=> 250, 'nombre' => 'Francia' , 'codigo_interno' => NULL],
            ['code'=> 266, 'nombre' => 'Gabón' , 'codigo_interno' => NULL],
            ['code'=> 270, 'nombre' => 'Gambia' , 'codigo_interno' => NULL],
            ['code'=> 268, 'nombre' => 'Georgia' , 'codigo_interno' => NULL],
            ['code'=> 239, 'nombre' => 'Islas Georgias del Sur y Sandwich del Sur' , 'codigo_interno' => NULL],
            ['code'=> 288, 'nombre' => 'Ghana' , 'codigo_interno' => NULL],
            ['code'=> 292, 'nombre' => 'Gibraltar' , 'codigo_interno' => NULL],
            ['code'=> 308, 'nombre' => 'Granada' , 'codigo_interno' => NULL],
            ['code'=> 300, 'nombre' => 'Grecia' , 'codigo_interno' => NULL],
            ['code'=> 304, 'nombre' => 'Groenlandia' , 'codigo_interno' => NULL],
            ['code'=> 312, 'nombre' => 'Guadalupe' , 'codigo_interno' => NULL],
            ['code'=> 316, 'nombre' => 'Guam' , 'codigo_interno' => NULL],
            ['code'=> 320, 'nombre' => 'Guatemala' , 'codigo_interno' => NULL],
            ['code'=> 254, 'nombre' => 'Guayana Francesa' , 'codigo_interno' => NULL],
            ['code'=> 324, 'nombre' => 'Guinea' , 'codigo_interno' => NULL],
            ['code'=> 226, 'nombre' => 'Guinea Ecuatorial' , 'codigo_interno' => NULL],
            ['code'=> 624, 'nombre' => 'Guinea-Bissau' , 'codigo_interno' => NULL],
            ['code'=> 328, 'nombre' => 'Guyana' , 'codigo_interno' => NULL],
            ['code'=> 332, 'nombre' => 'Haití' , 'codigo_interno' => NULL],
            ['code'=> 334, 'nombre' => 'Islas Heard y McDonald' , 'codigo_interno' => NULL],
            ['code'=> 340, 'nombre' => 'Honduras' , 'codigo_interno' => NULL],
            ['code'=> 344, 'nombre' => 'Hong Kong' , 'codigo_interno' => NULL],
            ['code'=> 348, 'nombre' => 'Hungría' , 'codigo_interno' => NULL],
            ['code'=> 356, 'nombre' => 'India' , 'codigo_interno' => NULL],
            ['code'=> 360, 'nombre' => 'Indonesia' , 'codigo_interno' => NULL],
            ['code'=> 364, 'nombre' => 'Irán' , 'codigo_interno' => NULL],
            ['code'=> 368, 'nombre' => 'Iraq' , 'codigo_interno' => NULL],
            ['code'=> 372, 'nombre' => 'Irlanda' , 'codigo_interno' => NULL],
            ['code'=> 352, 'nombre' => 'Islandia' , 'codigo_interno' => NULL],
            ['code'=> 376, 'nombre' => 'Israel' , 'codigo_interno' => NULL],
            ['code'=> 380, 'nombre' => 'Italia' , 'codigo_interno' => NULL],
            ['code'=> 388, 'nombre' => 'Jamaica' , 'codigo_interno' => NULL],
            ['code'=> 392, 'nombre' => 'Japón' , 'codigo_interno' => NULL],
            ['code'=> 400, 'nombre' => 'Jordania' , 'codigo_interno' => NULL],
            ['code'=> 398, 'nombre' => 'Kazajstán' , 'codigo_interno' => NULL],
            ['code'=> 404, 'nombre' => 'Kenia' , 'codigo_interno' => NULL],
            ['code'=> 417, 'nombre' => 'Kirguistán' , 'codigo_interno' => NULL],
            ['code'=> 296, 'nombre' => 'Kiribati' , 'codigo_interno' => NULL],
            ['code'=> 414, 'nombre' => 'Kuwait' , 'codigo_interno' => NULL],
            ['code'=> 418, 'nombre' => 'Laos' , 'codigo_interno' => NULL],
            ['code'=> 426, 'nombre' => 'Lesotho' , 'codigo_interno' => NULL],
            ['code'=> 428, 'nombre' => 'Letonia' , 'codigo_interno' => NULL],
            ['code'=> 422, 'nombre' => 'Líbano' , 'codigo_interno' => NULL],
            ['code'=> 430, 'nombre' => 'Liberia' , 'codigo_interno' => NULL],
            ['code'=> 434, 'nombre' => 'Libia' , 'codigo_interno' => NULL],
            ['code'=> 438, 'nombre' => 'Liechtenstein' , 'codigo_interno' => NULL],
            ['code'=> 440, 'nombre' => 'Lituania' , 'codigo_interno' => NULL],
            ['code'=> 442, 'nombre' => 'Luxemburgo' , 'codigo_interno' => NULL],
            ['code'=> 446, 'nombre' => 'Macao' , 'codigo_interno' => NULL],
            ['code'=> 807, 'nombre' => 'ARY Macedonia' , 'codigo_interno' => NULL],
            ['code'=> 450, 'nombre' => 'Madagascar' , 'codigo_interno' => NULL],
            ['code'=> 458, 'nombre' => 'Malasia' , 'codigo_interno' => NULL],
            ['code'=> 454, 'nombre' => 'Malawi' , 'codigo_interno' => NULL],
            ['code'=> 462, 'nombre' => 'Maldivas' , 'codigo_interno' => NULL],
            ['code'=> 466, 'nombre' => 'Malí' , 'codigo_interno' => NULL],
            ['code'=> 470, 'nombre' => 'Malta' , 'codigo_interno' => NULL],
            ['code'=> 238, 'nombre' => 'Islas Malvinas' , 'codigo_interno' => NULL],
            ['code'=> 580, 'nombre' => 'Islas Marianas del Norte' , 'codigo_interno' => NULL],
            ['code'=> 504, 'nombre' => 'Marruecos' , 'codigo_interno' => NULL],
            ['code'=> 584, 'nombre' => 'Islas Marshall' , 'codigo_interno' => NULL],
            ['code'=> 474, 'nombre' => 'Martinica' , 'codigo_interno' => NULL],
            ['code'=> 480, 'nombre' => 'Mauricio' , 'codigo_interno' => NULL],
            ['code'=> 478, 'nombre' => 'Mauritania' , 'codigo_interno' => NULL],
            ['code'=> 175, 'nombre' => 'Mayotte' , 'codigo_interno' => NULL],
            ['code'=> 484, 'nombre' => 'México' , 'codigo_interno' => NULL],
            ['code'=> 583, 'nombre' => 'Micronesia' , 'codigo_interno' => NULL],
            ['code'=> 498, 'nombre' => 'Moldavia' , 'codigo_interno' => NULL],
            ['code'=> 492, 'nombre' => 'Mónaco' , 'codigo_interno' => NULL],
            ['code'=> 496, 'nombre' => 'Mongolia' , 'codigo_interno' => NULL],
            ['code'=> 500, 'nombre' => 'Montserrat' , 'codigo_interno' => NULL],
            ['code'=> 508, 'nombre' => 'Mozambique' , 'codigo_interno' => NULL],
            ['code'=> 104, 'nombre' => 'Myanmar' , 'codigo_interno' => NULL],
            ['code'=> 516, 'nombre' => 'Namibia' , 'codigo_interno' => NULL],
            ['code'=> 520, 'nombre' => 'Nauru' , 'codigo_interno' => NULL],
            ['code'=> 524, 'nombre' => 'Nepal' , 'codigo_interno' => NULL],
            ['code'=> 558, 'nombre' => 'Nicaragua' , 'codigo_interno' => NULL],
            ['code'=> 562, 'nombre' => 'Níger' , 'codigo_interno' => NULL],
            ['code'=> 566, 'nombre' => 'Nigeria' , 'codigo_interno' => NULL],
            ['code'=> 570, 'nombre' => 'Niue' , 'codigo_interno' => NULL],
            ['code'=> 574, 'nombre' => 'Isla Norfolk' , 'codigo_interno' => NULL],
            ['code'=> 578, 'nombre' => 'Noruega' , 'codigo_interno' => NULL],
            ['code'=> 540, 'nombre' => 'Nueva Caledonia' , 'codigo_interno' => NULL],
            ['code'=> 554, 'nombre' => 'Nueva Zelanda' , 'codigo_interno' => NULL],
            ['code'=> 512, 'nombre' => 'Omán' , 'codigo_interno' => NULL],
            ['code'=> 528, 'nombre' => 'Países Bajos' , 'codigo_interno' => NULL],
            ['code'=> 586, 'nombre' => 'Pakistán' , 'codigo_interno' => NULL],
            ['code'=> 585, 'nombre' => 'Palau' , 'codigo_interno' => NULL],
            ['code'=> 275, 'nombre' => 'Palestina' , 'codigo_interno' => NULL],
            ['code'=> 591, 'nombre' => 'Panamá' , 'codigo_interno' => NULL],
            ['code'=> 598, 'nombre' => 'Papúa Nueva Guinea' , 'codigo_interno' => NULL],
            ['code'=> 600, 'nombre' => 'Paraguay' , 'codigo_interno' => NULL],
            ['code'=> 604, 'nombre' => 'Perú' , 'codigo_interno' => NULL],
            ['code'=> 612, 'nombre' => 'Islas Pitcairn' , 'codigo_interno' => NULL],
            ['code'=> 258, 'nombre' => 'Polinesia Francesa' , 'codigo_interno' => NULL],
            ['code'=> 616, 'nombre' => 'Polonia' , 'codigo_interno' => NULL],
            ['code'=> 620, 'nombre' => 'Portugal' , 'codigo_interno' => NULL],
            ['code'=> 630, 'nombre' => 'Puerto Rico' , 'codigo_interno' => NULL],
            ['code'=> 634, 'nombre' => 'Qatar' , 'codigo_interno' => NULL],
            ['code'=> 826, 'nombre' => 'Reino Unido' , 'codigo_interno' => NULL],
            ['code'=> 638, 'nombre' => 'Reunión' , 'codigo_interno' => NULL],
            ['code'=> 646, 'nombre' => 'Ruanda' , 'codigo_interno' => NULL],
            ['code'=> 642, 'nombre' => 'Rumania' , 'codigo_interno' => NULL],
            ['code'=> 643, 'nombre' => 'Rusia' , 'codigo_interno' => NULL],
            ['code'=> 732, 'nombre' => 'Sahara Occidental' , 'codigo_interno' => NULL],
            ['code'=> 90, 'nombre' => 'Islas Salomón' , 'codigo_interno' => NULL],
            ['code'=> 882, 'nombre' => 'Samoa' , 'codigo_interno' => NULL],
            ['code'=> 16, 'nombre' => 'Samoa Americana' , 'codigo_interno' => NULL],
            ['code'=> 659, 'nombre' => 'San Cristóbal y Nevis' , 'codigo_interno' => NULL],
            ['code'=> 674, 'nombre' => 'San Marino' , 'codigo_interno' => NULL],
            ['code'=> 666, 'nombre' => 'San Pedro y Miquelón' , 'codigo_interno' => NULL],
            ['code'=> 670, 'nombre' => 'San Vicente y las Granadinas' , 'codigo_interno' => NULL],
            ['code'=> 654, 'nombre' => 'Santa Helena' , 'codigo_interno' => NULL],
            ['code'=> 662, 'nombre' => 'Santa Lucía' , 'codigo_interno' => NULL],
            ['code'=> 678, 'nombre' => 'Santo Tomé y Príncipe' , 'codigo_interno' => NULL],
            ['code'=> 686, 'nombre' => 'Senegal' , 'codigo_interno' => NULL],
            ['code'=> 891, 'nombre' => 'Serbia y Montenegro' , 'codigo_interno' => NULL],
            ['code'=> 690, 'nombre' => 'Seychelles' , 'codigo_interno' => NULL],
            ['code'=> 694, 'nombre' => 'Sierra Leona' , 'codigo_interno' => NULL],
            ['code'=> 702, 'nombre' => 'Singapur' , 'codigo_interno' => NULL],
            ['code'=> 760, 'nombre' => 'Siria' , 'codigo_interno' => NULL],
            ['code'=> 706, 'nombre' => 'Somalia' , 'codigo_interno' => NULL],
            ['code'=> 144, 'nombre' => 'Sri Lanka' , 'codigo_interno' => NULL],
            ['code'=> 748, 'nombre' => 'Suazilandia' , 'codigo_interno' => NULL],
            ['code'=> 710, 'nombre' => 'Sudáfrica' , 'codigo_interno' => NULL],
            ['code'=> 736, 'nombre' => 'Sudán' , 'codigo_interno' => NULL],
            ['code'=> 752, 'nombre' => 'Suecia' , 'codigo_interno' => NULL],
            ['code'=> 756, 'nombre' => 'Suiza' , 'codigo_interno' => NULL],
            ['code'=> 740, 'nombre' => 'Surinam' , 'codigo_interno' => NULL],
            ['code'=> 744, 'nombre' => 'Svalbard y Jan Mayen' , 'codigo_interno' => NULL],
            ['code'=> 764, 'nombre' => 'Tailandia' , 'codigo_interno' => NULL],
            ['code'=> 158, 'nombre' => 'Taiwán' , 'codigo_interno' => NULL],
            ['code'=> 834, 'nombre' => 'Tanzania' , 'codigo_interno' => NULL],
            ['code'=> 762, 'nombre' => 'Tayikistán' , 'codigo_interno' => NULL],
            ['code'=> 86, 'nombre' => 'Territorio Británico del Océano Índico' , 'codigo_interno' => NULL],
            ['code'=> 260, 'nombre' => 'Territorios Australes Franceses' , 'codigo_interno' => NULL],
            ['code'=> 626, 'nombre' => 'Timor Oriental' , 'codigo_interno' => NULL],
            ['code'=> 768, 'nombre' => 'Togo' , 'codigo_interno' => NULL],
            ['code'=> 772, 'nombre' => 'Tokelau' , 'codigo_interno' => NULL],
            ['code'=> 776, 'nombre' => 'Tonga' , 'codigo_interno' => NULL],
            ['code'=> 780, 'nombre' => 'Trinidad y Tobago' , 'codigo_interno' => NULL],
            ['code'=> 788, 'nombre' => 'Túnez' , 'codigo_interno' => NULL],
            ['code'=> 796, 'nombre' => 'Islas Turcas y Caicos' , 'codigo_interno' => NULL],
            ['code'=> 795, 'nombre' => 'Turkmenistán' , 'codigo_interno' => NULL],
            ['code'=> 792, 'nombre' => 'Turquía' , 'codigo_interno' => NULL],
            ['code'=> 798, 'nombre' => 'Tuvalu' , 'codigo_interno' => NULL],
            ['code'=> 804, 'nombre' => 'Ucrania' , 'codigo_interno' => NULL],
            ['code'=> 800, 'nombre' => 'Uganda' , 'codigo_interno' => NULL],
            ['code'=> 858, 'nombre' => 'Uruguay' , 'codigo_interno' => NULL],
            ['code'=> 860, 'nombre' => 'Uzbekistán' , 'codigo_interno' => NULL],
            ['code'=> 548, 'nombre' => 'Vanuatu' , 'codigo_interno' => NULL],
            ['code'=> 862, 'nombre' => 'Venezuela' , 'codigo_interno' => NULL],
            ['code'=> 704, 'nombre' => 'Vietnam' , 'codigo_interno' => NULL],
            ['code'=> 92, 'nombre' => 'Islas Vírgenes Británicas' , 'codigo_interno' => NULL],
            ['code'=> 850, 'nombre' => 'Islas Vírgenes de los Estados Unidos' , 'codigo_interno' => NULL],
            ['code'=> 876, 'nombre' => 'Wallis y Futuna' , 'codigo_interno' => NULL],
            ['code'=> 887, 'nombre' => 'Yemen' , 'codigo_interno' => NULL],
            ['code'=> 262, 'nombre' => 'Yibuti' , 'codigo_interno' => NULL],
            ['code'=> 894, 'nombre' => 'Zambia' , 'codigo_interno' => NULL],
            ['code'=> 716, 'nombre' => 'Zimbabue' , 'codigo_interno' => NULL],
        ]);
    }
}
